### ISSUE TITLE
Can't resolve dependencies bug introduced with v6.3.1

### ISSUE THREAD

**Issue by cdupetit** [willsoto/nestjs-objection#106]
Hello,
This library is broken with the new version of nestjs v6.3.1.

> Nest can't resolve dependencies of the MyHealthIndicator (?). Please make sure that the argument at index [0] is available in the MyModule context.

See @kamilmysliwiec [comment](https://github.com/nestjs/nest/issues/2359#issuecomment-499638085) on nestjs/nest repo issue nestjs/nest#2359.
I've done a minimal repo [here](https://github.com/cdupetit/nestjs-issue-2359).
Best Regards

**Comment by willsoto** [comment]
Thanks for the report and links. I’ll try and fix this today.

**Comment by willsoto** [comment]
@cdupetit please test and let me know if this works. I didn't have a chance to write any tests to confirm it works.

**Comment by cdupetit** [comment]
@willsoto I've test and it works.
Thank you for the responsiveness.
