### ISSUE TITLE
Objection 3.0.0 Support

### ISSUE THREAD

**Issue by kasvith** [willsoto/nestjs-objection#1182]
Now Objection has released alpha versions for 3.0 and Knex >= 0.95

Is it possible to use these packages with `nest-objection` ?

Objection provides `objection@next` package version for alpha/beta/rc versions. Can `nest-objection` follow a similar pattern?

**Comment by willsoto** [comment]
I haven't been keeping track of the changes, so I am not really sure. If you are really anxious to try, Knex and Objection are `peerDependencies` of this package. You should be able to install whatever you want as long as you ignore the warnings about that. I can take a look maybe this weekend.

**Comment by kasvith** [comment]
Sure, maybe i will give a try to fix it

**Comment by kasvith** [comment]
thank you

**Comment by willsoto** [comment]
Let's leave this open until it's released.

**Comment by kasvith** [comment]
Cool makes sense
