### ISSUE TITLE
Different ways to import models

### ISSUE THREAD

**Issue by frenzymind** [willsoto/nestjs-objection#1579]
Hello. The official way to import model is:
`constructor(@Inject(User) private readonly userModel: typeof User) {}`
it also import User class at top of the file
`import { User } from "./user";`
I try to use userModel and User  and they looks identical. So I can minify my code not use Inject construction but only import statement.
Is there some difference? Should I use models through inject, why?
Thanks!

**Comment by willsoto** [comment]
You need to use `@Inject` because the `userModel` type is not the same as `User`. You have to inject the class token so the injector knows how to find, it but the injector isn't instantiating anything for you, hence the `typeof User` that you annotate `userModel` with.
