### ISSUE TITLE
Documentation "Recommended Way" load database configuration

### ISSUE THREAD

**Issue by semyon-san** [willsoto/nestjs-objection#1699]
In the documentation in database.ts file you have:
`export default registerAs("db", () => ({`

but it won't work because "db" should be "database":
`export default registerAs("database", () => ({`

**Comment by willsoto** [comment]
I don't see this line anywhere in the documentation. All I have is the README. Can you link to where you see this?

**Comment by semyon-san** [comment]
https://squareboat.com/open-source/nestjs-boilerplate/objection-setup#recommended-way

**Comment by semyon-san** [comment]
Sorry, it's the wrong project, got mixed up :)
