### ISSUE TITLE
ConfigModule and ConfigService examples

### ISSUE THREAD

**Issue by MrSparklle** [willsoto/nestjs-objection#564]
Will be fine if you can provide a simple example of ConfigModule and ConfigService files in the README

**Comment by willsoto** [comment]
Are you looking for what an example `ConfigService` might look like? This module doesn't have a preference, but if you are looking for examples, the NestJS docs have an entire [section dedicated to configuration](https://docs.nestjs.com/techniques/configuration).

Let me know if you are looking for anything specific.

**Comment by MrSparklle** [comment]
@willsoto config issue solved.
For now, I want to figure way out how to referrer a Objection Model to perform a simple query.

Something like `UserModel.query().findById(id).first();`

I'm trying to avoid using Knex query builder directly and use the Objection methods.

**Comment by willsoto** [comment]
You would need to refer to the Objection documentation then.

**Comment by MrSparklle** [comment]
I already did it, but Objection documentation didn't help to much.

Appreciate if you can help with a simple example.

**Comment by willsoto** [comment]
I am not sure how much more I can help you honestly. The [Objection.js documentation is excellent](https://vincit.github.io/objection.js/guide/query-examples.html#basic-queries) and provides tons of examples.

**Comment by KwabenBerko** [comment]
@willsoto 
Sorry if this is a dumb question, but
how do we inject an objection model? 

The current example shows only how to inject the underlying knex connection.

Any help will be appreciated.
Thanks.

**Comment by willsoto** [comment]
@KwabenBerko This library doesn't offer any special way to inject a model. You can use any of the styles [listed in the docs](https://docs.nestjs.com/fundamentals/custom-providers). Off the top of my head, something like this _should_ work:

```ts
import { MyModel } from "./my-model";

// Make sure this gets registered in a `@Module` somewhere
export const myModelProvider = {
  useValue: MyModel,
  provide: "MY_MODEL" // or you can use the token if you want
};
```

#### Usage

```ts
import { MyModel } from "./my-model";

@Injectable()
export class MyService {
  // use `typeof` because you want TS to know it's not an _instance_ but the class itself.
  constructor(@Inject("MY_MODEL") private MyModel: typeof MyModel) {}
}
```

Let me know if that works for you.

**Comment by KwabenBerko** [comment]
Okay Great.
Will try it out and get back to you.

**Comment by KwabenBerko** [comment]
@willsoto 
I followed something similar to what you suggested in a fork of this project and it worked. Thanks.
Ive submitted a PR based on that.
