### ISSUE TITLE
Multiple connections with @nestjs/config dependency

### ISSUE THREAD

**Issue by sergiopedrerobenedi** [willsoto/nestjs-objection#684]
Hi @willsoto.

Your module is really awesome!
But i have this problem:

I don't know how to implement multiple database connections with your module.
I need to use NestJS ConfigService for two database connections like this:

```
@Module(
  {
    imports: [ConfigModule.forFeature(firstDatabaseConfig),
      ObjectionModule.registerAsync({ imports: [ConfigModule],
        useFactory(config: ConfigService) {
          return {
            config: {
              ...config.get<knex.Config>('first-database-config'),
            },
          };
        },
        inject: [ConfigService] }), ObjectionModule.forFeature([FirstModel])], 
    controllers: [],
    exports: [ObjectionModule]},
)
export class FirstDatabaseModule {}
```
```
@Module(
  {
    imports: [ConfigModule.forFeature(secondDatabaseConfig),
      ObjectionModule.registerAsync({ imports: [ConfigModule],
        useFactory(config: ConfigService) {
          return {

            config: {
              ...config.get<knex.Config>('second-database-config'),

            },
          };
        },
        inject: [ConfigService] }), ObjectionModule.forFeature([SecondModel])], 
    controllers: [],
    exports: [ObjectionModule],

  },
)
export class FirstDatabaseModule {}
```

But when i make queries through each model,  always works with first database configuration.

Could you help me?
Thanks!

**Comment by willsoto** [comment]
@sergiopedrerobenedi What are your base classes? Do `FirstModel` and `SecondModel` share the same base class? Remember that objection binds itself to knex via `Model.knex(connection)`. And based on your code snippet both of your modules are being bound to the same subclass (since by default I use objection's default `Model` if none is provided). 

Can we start there and see if that fixes it?

**Comment by sergiopedrerobenedi** [comment]
Hi @willsoto , I setted different BaseClass to the different database connections, like you said.
I have a service, and I inject the two different models here.
When i query with the first model, it is running perfect. But when i query with the second model i have the next error:
```
[Nest] 62558   - 2020-07-09 14:13:28   [RpcExceptionsHandler] no database connection available for a query. You need to bind the model class or the query to a knex instance. +7003ms
Error: no database connection available for a query. You need to bind the model class or the query to a knex instance.
    at QueryBuilder.knex (/Users/sergiopedrerobenedi/Documents/Trabajo/CEFA/Proyectos/mobile-cefa-nest7-microservice-trace/node_modules/objection/lib/queryBuilder/QueryBuilderOperationSupport.js:206:15)
    at buildKnexQuery (/Users/sergiopedrerobenedi/Documents/Trabajo/CEFA/Proyectos/mobile-cefa-nest7-microservice-trace/node_modules/objection/lib/queryBuilder/QueryBuilder.js:1579:56)
    at doExecute (/Users/sergiopedrerobenedi/Documents/Trabajo/CEFA/Proyectos/mobile-cefa-nest7-microservice-trace/node_modules/objection/lib/queryBuilder/QueryBuilder.js:1470:31)
    at QueryBuilder.execute (/Users/sergiopedrerobenedi/Documents/Trabajo/CEFA/Proyectos/mobile-cefa-nest7-microservice-trace/node_modules/objection/lib/queryBuilder/QueryBuilder.js:682:28)
    at processTi
```

**Comment by willsoto** [comment]
Did you correctly [register each base class with this module? ](https://github.com/willsoto/nestjs-objection#configuration)

**Comment by sergiopedrerobenedi** [comment]
Yes , i did.
Like this?
```
import { Model } from 'objection';

export class BaseA extends Model {}
```

```
import { Model } from 'objection';

export class BaseB extends Model {}
```

And then in the modules

```
@Module(
  {
    imports: [ConfigModule.forFeature(firstDatabaseConfig),
      ObjectionModule.registerAsync({ imports: [ConfigModule],
        useFactory(config: ConfigService) {
          return {
            Model:BaseA,
            config: {
              ...config.get<knex.Config>('first-database-config'),
            },
          };
        },
        inject: [ConfigService] }), ObjectionModule.forFeature([FirstModel])], 
    controllers: [],
    exports: [ObjectionModule]},
)
export class FirstDatabaseModule {}
```

```

@Module(
  {
    imports: [ConfigModule.forFeature(secondDatabaseConfig),
      ObjectionModule.registerAsync({ imports: [ConfigModule],
        useFactory(config: ConfigService) {
          return {
            Model: BaseB
            config: {
              ...config.get<knex.Config>('second-database-config'),

            },
          };
        },
        inject: [ConfigService] }), ObjectionModule.forFeature([SecondModel])], 
    controllers: [],
    exports: [ObjectionModule],

  },
)
export class FirstDatabaseModule {}
```

**Comment by willsoto** [comment]
Yeah that looks right. I think I have an idea of what is going on here. I don't think registering the same module twice will have any effect. I'll have to add a way to support multiple connections.

I can make `register` and `registerAsync` accept an array of configurations. You will still have to have two base classes (that is just how objection works) but that should solve your use case.

**Comment by sergiopedrerobenedi** [comment]
It sounds really nice!
I look forward to hearing from you.
Thank you @willsoto

**Comment by willsoto** [comment]
Published under [v3.0.0](https://github.com/willsoto/nestjs-objection/releases/tag/v3.0.0)

**Comment by willsoto** [comment]
Documentation: https://github.com/willsoto/nestjs-objection#multiple-connections

**Comment by sergiopedrerobenedi** [comment]
Hello @willsoto !
It works fine but only one question.
When I import ObjectionModule into my DatabaseModule in the registerAsync function , VsCode tell me that 'name' property (database name property) not exists , but i can compile it and run it with different database instances good.
Thanks!

**Comment by willsoto** [comment]
Can you paste a code snippet please?

**Comment by sergiopedrerobenedi** [comment]
```
@Global()
@Module(
  {
    imports: [ConfigModule.forFeature(firstDatabaseConfig),
      ObjectionModule.registerAsync({
        name: 'connection1',
        imports: [ConfigModule],
        useFactory(config: ConfigService) {
          return {
            Model: BaseModelA,
            config: {
              ...config.get<knex.Config>('first-database-config'),

            },
          };
        },
        inject: [ConfigService],
      }),
```

Here I have a code error . VS Code says me (relative to name field):

```
Argument of type '{ name: string; imports: (typeof ConfigModule)[]; useFactory(config: ConfigService<Record<string, any>>): { Model: typeof HistoryBaseModel; config: any; }; inject: (typeof ConfigService)[]; }' is not assignable to parameter of type 'ObjectionModuleAsyncOptions'.
  Object literal may only specify known properties, and 'name' does not exist in type 'ObjectionModuleAsyncOptions'
```

**Comment by willsoto** [comment]
Does it compile outside of vscode? It could be that vscode's typings are cached

**Comment by sergiopedrerobenedi** [comment]
Ok, sorry! That is was what was happening!
Thanks!

**Comment by sergiopedrerobenedi** [comment]
And @willsoto in the docs section, in the second database connection config,  you wrote ```ObjectionCoreModule``` instead of this ``ÒbjectionModule```

**Comment by willsoto** [comment]
Whoops! Thanks, will fix.

**Comment by cdupetit** [comment]
Hello,
In your example, the connection manage only one Model. How can I configure multiple model in one of the two connection ?
Thanks in advance.
Regards

**Comment by willsoto** [comment]
@cdupetit you would need to provide two different base models, each bound to one of the different connections

**Comment by cdupetit** [comment]
How can I do that ? I have mulitple models defined like this : 

export class ItemModel1 extends objection.Model {
}

export class ItemModel2 extends objection.Model {
}

**Comment by willsoto** [comment]
It's here in the example: https://github.com/willsoto/nestjs-objection#multiple-connections

`export class BaseModelConnection1 extends objection.Model {}`
`export class BaseModelConnection2 extends objection.Model {}`

**Comment by cdupetit** [comment]
Yes but  I have mulitple tables (models) in the database.

**Comment by willsoto** [comment]
`export class MyModel1 extends BaseModelConnection1 {}`
`export class MyModel2 extends BaseModelConnection2 {}`

https://vincit.github.io/objection.js/recipes/multitenancy-using-multiple-databases.html#model-binding-pattern

**Comment by cdupetit** [comment]
Thanks. I will try the binding pattern.
